
{% set name = "scraps" %}
{% set version = "0.5.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/scraps-{{ version }}.tar.gz
  sha256: 3a41aecab60f8cfc57aa4cf8010d987f4e8d4c9fdac0f01b192e61af92d42446

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - emcee >=2.2.1
    - lmfit >=0.9.5
    - matplotlib-base >=2.0
    - numpy >=1.5
    - pandas >=0.18
    - python >={{ python_min }}
    - scipy >=0.14

test:
  requires:
    - python {{ python_min }}
  imports:
    - scraps

about:
  home: http://github.com/FaustinCarter/scraps
  summary: SuperConducting Resonator Analysis and Plotting Software.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - FaustinCarter
